png(filename = "plot4.png")
par(mfrow = c(2,2))
plot(opdata$DateTime, opdata$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power")
plot(opdata$DateTime, opdata$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(opdata$DateTime, opdata$Sub_metering_1, type = "l", col = "black", xlab = "", ylab = "Energy sub metering")
lines(opdata$DateTime, opdata$Sub_metering_2, col = "red")
lines(opdata$DateTime, opdata$Sub_metering_3, col = "blue")
legend("topright", col = c("black", "red", "blue"), c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lwd = 1)
plot(opdata$DateTime, opdata$Global_reactive_power, type = "l", col = "black", xlab = "datetime", ylab = "Global_reactive_power")
dev.off()